### PR TITLE
update multicodec table

### PR DESCRIPTION
**Pull request by TimoGlastra**
This PR updates the multicodec file based on the newest csv in the multicodec repo.

The current release misses quite some new additions (I'm particularly interested in the key formats)

### CODE REVIEW

**Comment by TimoGlastra** [comment]
The tests contained an invalid code to test against that is now valid. Updated

**Comment by TimoGlastra** [comment]
The Python3.5 build is still failing, but it seems like that was already the case before this PR and unrelated to this change.

**Comment by dhruvbaldawa** [comment]
Thanks for doing this!

**Comment by TimoGlastra** [comment]
Thanks for merging! Could you maybe do a new release so I can use the PyPi version? That would be much appreciated!

**Pull request merged**
